site_name: Chaos Monkey
site_url: https://netflix.github.io/chaosmonkey
repo_url: https://github.com/Netflix/chaosmonkey
theme: readthedocs
copyright: <b>A Netflix Original Production</b><br><a href="http://netflix.github.io/">Netflix OSS</a> | <a href="http://techblog.netflix.com/">Tech Blog</a> | <a href="https://twitter.com/NetflixOSS">Twitter @NetflixOSS</a> | <a href="https://jobs.netflix.com">Jobs</a>
